version: '3.9'
services:
  service1:
    container_name: node_cont
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'
  db:
    image: 'postgres:latest'
    container_name: db_cont
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_USER: 'docker'
